import type {
  MCTask,
  MCEvent,
  MCAgentStatus,
  MCSession,
  MCMetrics,
  MCComment,
  MCReview,
  MCActivity,
} from "@/types/mission-control";

// ─── Helper ───────────────────────────────────────────────
function ago(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

// ─── Mock Metrics ─────────────────────────────────────────
export const mockMetrics: MCMetrics = {
  system_health_percent: 94.5,
  active_agents: 3,
  total_agents: 5,
  tasks_in_progress: 4,
  tasks_completed_today: 12,
  cost_today_usd: 12.45,
  success_rate_percent: 89.2,
};

// ─── Mock Agent Statuses ──────────────────────────────────
export const mockAgentStatuses: MCAgentStatus[] = [
  {
    id: "as-1",
    user_id: "demo",
    agent_id: "agent-1",
    agent: { id: "agent-1", name: "Support Bot", description: "Handles customer support tickets" },
    status: "working",
    current_task_id: "task-3",
    current_task: { id: "task-3", title: "Process refund requests" },
    capacity_used: 75,
    performance_score: 92.5,
    last_activity_at: ago(1),
    metadata: { version: "1.2.3", deployed_tools: ["send_email", "query_db", "slack_notify"] },
    updated_at: ago(0),
  },
  {
    id: "as-2",
    user_id: "demo",
    agent_id: "agent-2",
    agent: { id: "agent-2", name: "Research Bot", description: "Performs web research and analysis" },
    status: "idle",
    current_task_id: null,
    current_task: null,
    capacity_used: 0,
    performance_score: 88.0,
    last_activity_at: ago(15),
    metadata: { version: "1.2.3", deployed_tools: ["web_search", "parse_pdf", "summarize"] },
    updated_at: ago(5),
  },
  {
    id: "as-3",
    user_id: "demo",
    agent_id: "agent-3",
    agent: { id: "agent-3", name: "Writer Bot", description: "Creates content and documentation" },
    status: "working",
    current_task_id: "task-7",
    current_task: { id: "task-7", title: "Write monthly newsletter" },
    capacity_used: 40,
    performance_score: 95.0,
    last_activity_at: ago(2),
    metadata: { version: "1.3.0", deployed_tools: ["text_gen", "image_gen", "format_doc"] },
    updated_at: ago(0),
  },
  {
    id: "as-4",
    user_id: "demo",
    agent_id: "agent-4",
    agent: { id: "agent-4", name: "Analyst Bot", description: "Data analysis and reporting" },
    status: "blocked",
    current_task_id: "task-9",
    current_task: { id: "task-9", title: "Quarterly revenue analysis" },
    capacity_used: 100,
    performance_score: 45.0,
    last_activity_at: ago(30),
    metadata: { version: "1.1.0", deployed_tools: ["query_db", "chart_gen", "export_csv"] },
    updated_at: ago(10),
  },
  {
    id: "as-5",
    user_id: "demo",
    agent_id: "agent-5",
    agent: { id: "agent-5", name: "Code Bot", description: "Code review and generation" },
    status: "sleeping",
    current_task_id: null,
    current_task: null,
    capacity_used: 0,
    performance_score: 91.0,
    last_activity_at: ago(120),
    metadata: { version: "2.0.0", deployed_tools: ["code_gen", "lint", "test_runner", "git_commit"] },
    updated_at: ago(60),
  },
];

// ─── Mock Tasks ───────────────────────────────────────────
export const mockTasks: MCTask[] = [
  // Planning
  {
    id: "task-1",
    user_id: "demo",
    title: "Review new signup applications",
    description: "Check and verify 15 new customer signup requests from the last 24 hours.",
    column_id: "planning",
    priority: "medium",
    assigned_agent_id: null,
    assigned_agent: null,
    created_by: "system",
    due_date: null,
    estimated_hours: 2,
    actual_hours: null,
    position: 0,
    acceptance_criteria: "All signups reviewed, flagged or approved",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: { tags: ["admin", "onboarding"] },
    created_at: ago(30),
    updated_at: ago(30),
    completed_at: null,
  },
  {
    id: "task-2",
    user_id: "demo",
    title: "Investigate API latency spike",
    description: "p99 latency jumped from 200ms to 1.2s at 14:00 UTC. Find root cause.",
    column_id: "planning",
    priority: "high",
    assigned_agent_id: null,
    assigned_agent: null,
    created_by: "user",
    due_date: ago(-120),
    estimated_hours: 4,
    actual_hours: null,
    position: 1,
    acceptance_criteria: "Root cause identified and documented",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: { tags: ["infrastructure", "urgent"] },
    created_at: ago(15),
    updated_at: ago(15),
    completed_at: null,
  },
  // Inbox (ready for pickup)
  {
    id: "task-3",
    user_id: "demo",
    title: "Process refund requests",
    description: "Review and approve 8 refund requests from last week. Total: $472.",
    column_id: "inbox",
    priority: "high",
    assigned_agent_id: null,
    assigned_agent: null,
    created_by: "system",
    due_date: ago(-60),
    estimated_hours: 3,
    actual_hours: null,
    position: 0,
    acceptance_criteria: "All refunds processed or escalated",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: { tags: ["billing", "support"] },
    created_at: ago(60),
    updated_at: ago(20),
    completed_at: null,
  },
  {
    id: "task-4",
    user_id: "demo",
    title: "Update pricing page copy",
    description: "Reflect new Ultra tier pricing and features on the marketing site.",
    column_id: "inbox",
    priority: "medium",
    assigned_agent_id: null,
    assigned_agent: null,
    created_by: "user",
    due_date: ago(-480),
    estimated_hours: 2,
    actual_hours: null,
    position: 1,
    acceptance_criteria: "Copy updated, reviewed, deployed",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: { tags: ["marketing", "content"] },
    created_at: ago(180),
    updated_at: ago(180),
    completed_at: null,
  },
  // Assigned
  {
    id: "task-13",
    user_id: "demo",
    title: "Set up monitoring alerts",
    description: "Configure alerts for CPU > 90%, memory > 85%, and disk > 80% on all VPS instances.",
    column_id: "assigned",
    priority: "high",
    assigned_agent_id: "agent-5",
    assigned_agent: { id: "agent-5", name: "Code Bot" },
    created_by: "system",
    due_date: ago(-240),
    estimated_hours: 3,
    actual_hours: null,
    position: 0,
    acceptance_criteria: "Alerts fire correctly for all thresholds",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: { tags: ["infrastructure", "monitoring"] },
    created_at: ago(90),
    updated_at: ago(45),
    completed_at: null,
  },
  // In Progress
  {
    id: "task-5",
    user_id: "demo",
    title: "Generate March analytics report",
    description: "Compile usage analytics, revenue, and growth metrics for March 2026.",
    column_id: "in_progress",
    priority: "high",
    assigned_agent_id: "agent-4",
    assigned_agent: { id: "agent-4", name: "Analyst Bot" },
    created_by: "system",
    due_date: ago(-30),
    estimated_hours: 6,
    actual_hours: 3,
    position: 0,
    acceptance_criteria: "Report generated with charts, exported as PDF",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: {
      tags: ["analytics", "monthly"],
      subtasks: [
        { id: "s1", title: "Export raw data", completed: true },
        { id: "s2", title: "Generate charts", completed: true },
        { id: "s3", title: "Write summary", completed: false },
        { id: "s4", title: "Format PDF", completed: false },
      ],
    },
    created_at: ago(120),
    updated_at: ago(5),
    completed_at: null,
  },
  {
    id: "task-6",
    user_id: "demo",
    title: "Draft customer onboarding email sequence",
    description: "Create 5-email drip campaign for new Ultra tier customers.",
    column_id: "in_progress",
    priority: "medium",
    assigned_agent_id: "agent-3",
    assigned_agent: { id: "agent-3", name: "Writer Bot" },
    created_by: "user",
    due_date: ago(-240),
    estimated_hours: 8,
    actual_hours: 4,
    position: 1,
    acceptance_criteria: "5 emails drafted, reviewed, loaded into ESP",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: { tags: ["marketing", "email"] },
    created_at: ago(240),
    updated_at: ago(10),
    completed_at: null,
  },
  {
    id: "task-7",
    user_id: "demo",
    title: "Write monthly newsletter",
    description: "March 2026 newsletter covering new features, tips, and community spotlight.",
    column_id: "in_progress",
    priority: "low",
    assigned_agent_id: "agent-3",
    assigned_agent: { id: "agent-3", name: "Writer Bot" },
    created_by: "system",
    due_date: ago(-1440),
    estimated_hours: 4,
    actual_hours: 2,
    position: 2,
    acceptance_criteria: "Newsletter written and approved",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: { tags: ["content"] },
    created_at: ago(300),
    updated_at: ago(2),
    completed_at: null,
  },
  {
    id: "task-8",
    user_id: "demo",
    title: "Resolve webhook timeout issue",
    description: "Customer reported Stripe webhooks timing out after 10s. Increase to 30s.",
    column_id: "in_progress",
    priority: "critical",
    assigned_agent_id: "agent-1",
    assigned_agent: { id: "agent-1", name: "Support Bot" },
    created_by: "Support Bot",
    due_date: ago(-15),
    estimated_hours: 1,
    actual_hours: null,
    position: 3,
    acceptance_criteria: "Timeout increased, verified with test webhook",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: { tags: ["bug", "infrastructure"] },
    created_at: ago(45),
    updated_at: ago(8),
    completed_at: null,
  },
  // Testing
  {
    id: "task-14",
    user_id: "demo",
    title: "Build automated backup script",
    description: "Create daily backup script for all customer databases with retention policy.",
    column_id: "testing",
    priority: "high",
    assigned_agent_id: "agent-5",
    assigned_agent: { id: "agent-5", name: "Code Bot" },
    created_by: "user",
    due_date: ago(-120),
    estimated_hours: 5,
    actual_hours: 4,
    position: 0,
    acceptance_criteria: "Backup runs daily, restores verified, 30-day retention",
    outcome: null,
    error_message: null,
    resolution: null,
    metadata: {
      tags: ["infrastructure", "automation"],
      subtasks: [
        { id: "s1", title: "Write backup script", completed: true },
        { id: "s2", title: "Add retention policy", completed: true },
        { id: "s3", title: "Test restore process", completed: false },
        { id: "s4", title: "Set up cron job", completed: false },
      ],
    },
    created_at: ago(360),
    updated_at: ago(15),
    completed_at: null,
  },
  // Review
  {
    id: "task-9",
    user_id: "demo",
    title: "Quarterly revenue analysis",
    description: "Q1 2026 revenue breakdown by tier, region, and channel.",
    column_id: "review",
    priority: "high",
    assigned_agent_id: "agent-4",
    assigned_agent: { id: "agent-4", name: "Analyst Bot" },
    created_by: "system",
    due_date: ago(-60),
    estimated_hours: 8,
    actual_hours: 7,
    position: 0,
    acceptance_criteria: "Analysis accurate, charts clear, exec summary included",
    outcome: "Q1 revenue up 23% YoY. Ultra tier accounts for 45% of new MRR.",
    error_message: null,
    resolution: null,
    metadata: { tags: ["analytics", "quarterly"] },
    created_at: ago(360),
    updated_at: ago(30),
    completed_at: null,
  },
  {
    id: "task-10",
    user_id: "demo",
    title: "Code review: auth middleware refactor",
    description: "Review PR #142 for the authentication middleware refactor.",
    column_id: "review",
    priority: "medium",
    assigned_agent_id: "agent-5",
    assigned_agent: { id: "agent-5", name: "Code Bot" },
    created_by: "Code Bot",
    due_date: ago(-120),
    estimated_hours: 2,
    actual_hours: 1,
    position: 1,
    acceptance_criteria: "PR approved or feedback provided",
    outcome: "PR reviewed — 3 suggestions, no blockers",
    error_message: null,
    resolution: null,
    metadata: { tags: ["engineering", "review"] },
    created_at: ago(480),
    updated_at: ago(60),
    completed_at: null,
  },
  // Done
  {
    id: "task-11",
    user_id: "demo",
    title: "Deploy SSL certificate renewal",
    description: "Auto-renew Let's Encrypt certs for all customer subdomains.",
    column_id: "done",
    priority: "high",
    assigned_agent_id: "agent-5",
    assigned_agent: { id: "agent-5", name: "Code Bot" },
    created_by: "system",
    due_date: null,
    estimated_hours: 4,
    actual_hours: 3,
    position: 0,
    acceptance_criteria: "All certs renewed, no downtime",
    outcome: "47 certificates renewed successfully. Zero downtime.",
    error_message: null,
    resolution: "Automated via certbot cron job + nginx reload",
    metadata: { tags: ["infrastructure", "ssl"] },
    created_at: ago(1440),
    updated_at: ago(720),
    completed_at: ago(720),
  },
  {
    id: "task-12",
    user_id: "demo",
    title: "Respond to 12 support tickets",
    description: "Handle queue of open support tickets from the weekend.",
    column_id: "done",
    priority: "medium",
    assigned_agent_id: "agent-1",
    assigned_agent: { id: "agent-1", name: "Support Bot" },
    created_by: "system",
    due_date: null,
    estimated_hours: 3,
    actual_hours: 2,
    position: 1,
    acceptance_criteria: "All tickets resolved or escalated",
    outcome: "12/12 tickets resolved. 2 escalated to engineering.",
    error_message: null,
    resolution: "Resolved via automated responses and manual follow-up",
    metadata: { tags: ["support"] },
    created_at: ago(2880),
    updated_at: ago(1440),
    completed_at: ago(1440),
  },
];

// ─── Mock Comments ────────────────────────────────────────
export const mockComments: MCComment[] = [
  {
    id: "cmt-1",
    task_id: "task-9",
    author: "Analyst Bot",
    content: "Initial data export complete. Found discrepancy in Q1 revenue figures — investigating.",
    created_at: ago(120),
    parent_id: null,
    mentions: [],
  },
  {
    id: "cmt-2",
    task_id: "task-9",
    author: "user",
    content: "Make sure to include the Ultra tier breakdown separately.",
    created_at: ago(90),
    parent_id: null,
    mentions: ["Analyst Bot"],
  },
  {
    id: "cmt-3",
    task_id: "task-9",
    author: "Analyst Bot",
    content: "Done — Ultra tier now has its own section with MRR, churn, and expansion metrics.",
    created_at: ago(60),
    parent_id: "cmt-2",
    mentions: [],
  },
  {
    id: "cmt-4",
    task_id: "task-5",
    author: "Analyst Bot",
    content: "Charts generated. Working on executive summary now.",
    created_at: ago(10),
    parent_id: null,
    mentions: [],
  },
  {
    id: "cmt-5",
    task_id: "task-8",
    author: "Support Bot",
    content: "Found the issue — webhook handler has a hardcoded 10s timeout. Updating to 30s.",
    created_at: ago(12),
    parent_id: null,
    mentions: [],
  },
  {
    id: "cmt-6",
    task_id: "task-10",
    author: "Code Bot",
    content: "PR looks good overall. Three minor suggestions:\n1. Extract token validation to utility\n2. Add rate limiting middleware\n3. Update error messages to be more descriptive",
    created_at: ago(65),
    parent_id: null,
    mentions: [],
  },
];

// ─── Mock Reviews ─────────────────────────────────────────
export const mockReviews: MCReview[] = [
  {
    id: "rev-1",
    task_id: "task-9",
    reviewer: "user",
    status: "needs_changes",
    notes: "Revenue figures look correct but charts need better labeling. Add axis titles and data labels.",
    created_at: ago(45),
  },
  {
    id: "rev-2",
    task_id: "task-10",
    reviewer: "user",
    status: "approved",
    notes: "Code review feedback is thorough. Approve the refactor.",
    created_at: ago(55),
  },
  {
    id: "rev-3",
    task_id: "task-11",
    reviewer: "user",
    status: "approved",
    notes: "All 47 certs renewed, verified no downtime. Great work.",
    created_at: ago(730),
  },
  {
    id: "rev-4",
    task_id: "task-12",
    reviewer: "user",
    status: "approved",
    notes: null,
    created_at: ago(1450),
  },
];

// ─── Mock Activities ──────────────────────────────────────
export const mockActivities: MCActivity[] = [
  {
    id: "act-1",
    task_id: "task-9",
    actor: "Analyst Bot",
    action: "changed_status",
    old_value: "in_progress",
    new_value: "review",
    created_at: ago(35),
  },
  {
    id: "act-2",
    task_id: "task-9",
    actor: "user",
    action: "added_review",
    old_value: null,
    new_value: "needs_changes",
    created_at: ago(45),
  },
  {
    id: "act-3",
    task_id: "task-5",
    actor: "Analyst Bot",
    action: "completed_subtask",
    old_value: null,
    new_value: "Generate charts",
    created_at: ago(10),
  },
  {
    id: "act-4",
    task_id: "task-8",
    actor: "system",
    action: "assigned_agent",
    old_value: null,
    new_value: "Support Bot",
    created_at: ago(45),
  },
  {
    id: "act-5",
    task_id: "task-8",
    actor: "Support Bot",
    action: "changed_status",
    old_value: "assigned",
    new_value: "in_progress",
    created_at: ago(40),
  },
  {
    id: "act-6",
    task_id: "task-11",
    actor: "Code Bot",
    action: "changed_status",
    old_value: "review",
    new_value: "done",
    created_at: ago(720),
  },
  {
    id: "act-7",
    task_id: "task-14",
    actor: "Code Bot",
    action: "changed_status",
    old_value: "in_progress",
    new_value: "testing",
    created_at: ago(15),
  },
  {
    id: "act-8",
    task_id: "task-13",
    actor: "system",
    action: "assigned_agent",
    old_value: null,
    new_value: "Code Bot",
    created_at: ago(45),
  },
];

// ─── Mock Events ──────────────────────────────────────────
export const mockEvents: MCEvent[] = [
  {
    id: "evt-1",
    user_id: "demo",
    event_type: "task_complete",
    severity: "success",
    agent_id: "agent-1",
    agent: { id: "agent-1", name: "Support Bot" },
    task_id: "task-12",
    session_id: null,
    message: "Completed: Respond to 12 support tickets",
    payload: { duration_ms: 45000, tasks_resolved: 12 },
    created_at: ago(2),
  },
  {
    id: "evt-2",
    user_id: "demo",
    event_type: "tool_invocation",
    severity: "info",
    agent_id: "agent-3",
    agent: { id: "agent-3", name: "Writer Bot" },
    task_id: "task-7",
    session_id: null,
    message: "Invoked tool: text_gen — generating newsletter section 3/5",
    payload: { tool: "text_gen", section: 3, total: 5 },
    created_at: ago(3),
  },
  {
    id: "evt-3",
    user_id: "demo",
    event_type: "error",
    severity: "error",
    agent_id: "agent-4",
    agent: { id: "agent-4", name: "Analyst Bot" },
    task_id: "task-9",
    session_id: null,
    message: "Database query timeout after 30s — quarterly_revenue view",
    payload: { error_code: "QUERY_TIMEOUT", query: "SELECT * FROM quarterly_revenue...", retry_count: 2 },
    created_at: ago(5),
  },
  {
    id: "evt-4",
    user_id: "demo",
    event_type: "agent_state_change",
    severity: "info",
    agent_id: "agent-2",
    agent: { id: "agent-2", name: "Research Bot" },
    task_id: null,
    session_id: null,
    message: "Status changed: working → idle",
    payload: { from: "working", to: "idle", reason: "task_complete" },
    created_at: ago(8),
  },
  {
    id: "evt-5",
    user_id: "demo",
    event_type: "webhook",
    severity: "info",
    agent_id: null,
    agent: null,
    task_id: null,
    session_id: null,
    message: "Stripe webhook: payment_intent.succeeded — $350.00",
    payload: { event: "payment_intent.succeeded", amount: 35000, currency: "usd" },
    created_at: ago(12),
  },
  {
    id: "evt-6",
    user_id: "demo",
    event_type: "session_start",
    severity: "info",
    agent_id: "agent-1",
    agent: { id: "agent-1", name: "Support Bot" },
    task_id: "task-8",
    session_id: "sess-1",
    message: "Session started for task: Resolve webhook timeout issue",
    payload: { model: "Kimi K2.5" },
    created_at: ago(15),
  },
  {
    id: "evt-7",
    user_id: "demo",
    event_type: "tool_invocation",
    severity: "info",
    agent_id: "agent-1",
    agent: { id: "agent-1", name: "Support Bot" },
    task_id: "task-8",
    session_id: "sess-1",
    message: "Invoked tool: query_db — checking webhook config",
    payload: { tool: "query_db", query: "SELECT timeout FROM webhook_configs..." },
    created_at: ago(14),
  },
  {
    id: "evt-8",
    user_id: "demo",
    event_type: "error",
    severity: "warning",
    agent_id: "agent-3",
    agent: { id: "agent-3", name: "Writer Bot" },
    task_id: "task-6",
    session_id: null,
    message: "Rate limit warning: 80% of hourly token budget consumed",
    payload: { tokens_used: 80000, tokens_limit: 100000, reset_in_minutes: 22 },
    created_at: ago(18),
  },
  {
    id: "evt-9",
    user_id: "demo",
    event_type: "task_complete",
    severity: "success",
    agent_id: "agent-5",
    agent: { id: "agent-5", name: "Code Bot" },
    task_id: "task-11",
    session_id: null,
    message: "Completed: Deploy SSL certificate renewal — 47 certs renewed",
    payload: { certs_renewed: 47, duration_ms: 120000 },
    created_at: ago(25),
  },
  {
    id: "evt-10",
    user_id: "demo",
    event_type: "agent_state_change",
    severity: "info",
    agent_id: "agent-4",
    agent: { id: "agent-4", name: "Analyst Bot" },
    task_id: "task-9",
    session_id: null,
    message: "Status changed: working → blocked (awaiting approval)",
    payload: { from: "working", to: "blocked", reason: "needs_approval" },
    created_at: ago(30),
  },
  {
    id: "evt-11",
    user_id: "demo",
    event_type: "webhook",
    severity: "info",
    agent_id: null,
    agent: null,
    task_id: null,
    session_id: null,
    message: "GitHub webhook: push to main — 3 commits",
    payload: { event: "push", branch: "main", commits: 3 },
    created_at: ago(35),
  },
  {
    id: "evt-12",
    user_id: "demo",
    event_type: "session_end",
    severity: "success",
    agent_id: "agent-2",
    agent: { id: "agent-2", name: "Research Bot" },
    task_id: null,
    session_id: "sess-2",
    message: "Session ended — 1,200 tokens, $0.04, 3m 12s",
    payload: { tokens_input: 800, tokens_output: 400, cost_usd: 0.04, duration_ms: 192000 },
    created_at: ago(40),
  },
];

// ─── Mock Sessions ────────────────────────────────────────
export const mockSessions: MCSession[] = [
  {
    id: "sess-1",
    user_id: "demo",
    agent_id: "agent-1",
    agent: { id: "agent-1", name: "Support Bot" },
    task_id: "task-8",
    task: { id: "task-8", title: "Resolve webhook timeout issue" },
    started_at: ago(15),
    ended_at: null,
    duration_ms: null,
    tokens_input: 650,
    tokens_output: 280,
    cost_usd: 0.023,
    success: true,
    error_message: null,
    trace_data: {
      steps: [
        { timestamp: ago(15), action: "Initialize session", result: "success", duration_ms: 200, cost_usd: 0.001 },
        { timestamp: ago(14), action: "Query webhook config", result: "success", duration_ms: 1500, cost_usd: 0.008 },
        { timestamp: ago(13), action: "Analyze timeout settings", result: "success", duration_ms: 2100, cost_usd: 0.014 },
      ],
    },
  },
  {
    id: "sess-2",
    user_id: "demo",
    agent_id: "agent-2",
    agent: { id: "agent-2", name: "Research Bot" },
    task_id: null,
    task: null,
    started_at: ago(55),
    ended_at: ago(40),
    duration_ms: 192000,
    tokens_input: 800,
    tokens_output: 400,
    cost_usd: 0.04,
    success: true,
    error_message: null,
    trace_data: {
      steps: [
        { timestamp: ago(55), action: "Web search: competitor pricing", result: "5 results found", duration_ms: 3200, cost_usd: 0.0 },
        { timestamp: ago(52), action: "Parse search results", result: "success", duration_ms: 1400, cost_usd: 0.012 },
        { timestamp: ago(48), action: "Generate summary", result: "success", duration_ms: 2100, cost_usd: 0.028 },
      ],
    },
  },
  {
    id: "sess-3",
    user_id: "demo",
    agent_id: "agent-3",
    agent: { id: "agent-3", name: "Writer Bot" },
    task_id: "task-7",
    task: { id: "task-7", title: "Write monthly newsletter" },
    started_at: ago(30),
    ended_at: null,
    duration_ms: null,
    tokens_input: 2400,
    tokens_output: 1800,
    cost_usd: 0.089,
    success: true,
    error_message: null,
    trace_data: {
      steps: [
        { timestamp: ago(30), action: "Outline newsletter sections", result: "5 sections planned", duration_ms: 1800, cost_usd: 0.015 },
        { timestamp: ago(27), action: "Write section 1: Feature spotlight", result: "success", duration_ms: 4500, cost_usd: 0.022 },
        { timestamp: ago(20), action: "Write section 2: Tips & tricks", result: "success", duration_ms: 3800, cost_usd: 0.019 },
        { timestamp: ago(10), action: "Write section 3: Community", result: "in progress", duration_ms: 0, cost_usd: 0.033 },
      ],
    },
  },
  {
    id: "sess-4",
    user_id: "demo",
    agent_id: "agent-4",
    agent: { id: "agent-4", name: "Analyst Bot" },
    task_id: "task-5",
    task: { id: "task-5", title: "Generate March analytics report" },
    started_at: ago(120),
    ended_at: ago(90),
    duration_ms: 1800000,
    tokens_input: 5200,
    tokens_output: 3100,
    cost_usd: 0.21,
    success: true,
    error_message: null,
    trace_data: {
      steps: [
        { timestamp: ago(120), action: "Export raw data from DB", result: "success", duration_ms: 8000, cost_usd: 0.0 },
        { timestamp: ago(115), action: "Generate revenue chart", result: "success", duration_ms: 12000, cost_usd: 0.05 },
        { timestamp: ago(105), action: "Generate user growth chart", result: "success", duration_ms: 10000, cost_usd: 0.045 },
        { timestamp: ago(100), action: "Calculate key metrics", result: "success", duration_ms: 5000, cost_usd: 0.035 },
        { timestamp: ago(95), action: "Write executive summary", result: "success", duration_ms: 15000, cost_usd: 0.08 },
      ],
    },
  },
  {
    id: "sess-5",
    user_id: "demo",
    agent_id: "agent-4",
    agent: { id: "agent-4", name: "Analyst Bot" },
    task_id: "task-9",
    task: { id: "task-9", title: "Quarterly revenue analysis" },
    started_at: ago(60),
    ended_at: null,
    duration_ms: null,
    tokens_input: 1800,
    tokens_output: 500,
    cost_usd: 0.065,
    success: false,
    error_message: "Database query timeout — quarterly_revenue view",
    trace_data: {
      steps: [
        { timestamp: ago(60), action: "Query quarterly_revenue view", result: "timeout after 30s", duration_ms: 30000, cost_usd: 0.0 },
        { timestamp: ago(55), action: "Retry query with reduced scope", result: "timeout after 30s", duration_ms: 30000, cost_usd: 0.0 },
        { timestamp: ago(50), action: "Report failure — needs approval to retry", result: "blocked", duration_ms: 500, cost_usd: 0.065 },
      ],
    },
  },
];
